// Generated by tonic_build / prost from proto/inference.proto. Loosen
// clippy here — codegen output isn't subject to our style rules.
#![allow(
    clippy::enum_variant_names,
    clippy::derive_partial_eq_without_eq,
    clippy::large_enum_variant,
    clippy::doc_markdown
)]

tonic::include_proto!("inference");
